name: Lint Test

on:
  push:
    branches:
      - dev
      - main
      - staging
  pull_request:
    branches:
      - dev
      - main
      - staging

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Clean Install
        run: npm ci

      - name: Build
        run: npm run build --if-present
        
      - name: Unit Tests
        run: npm run test --if-present

      - name: Lint
        run: npm run lint
